language: python
node_js:
  - "0.10.25"
before_install:
  - npm install -g jshint csslint phantomjs-prebuilt node-qunit-phantomjs js-beautify jasmine-node
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - flake8 apps/
  - jshint apps/movies/static/movies/js/
  - csslint apps/movies/static/movies/css/app.css
  - phantomjs -v
  - node-qunit-phantomjs apps/movies/static/movies/test/test.html --verbose
  - js-beautify -r apps/movies/static/movies/js/*.js
  - jasmine-node apps/movies/static/movies/test/spec/
