language: python
node_js:
  - "0.10.25"
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - npm install -g
# command to run tests
script:
  - flake8 apps/
  - python apps/manage.py test movies
  - jshint apps/movies/static/movies/js/
  - csslint apps/movies/static/movies/css/app.css
  - css-beautify -r apps/movies/static/movies/css/app.css
  - html-beautify -r apps/movies/templates/movies/index.html
  - html-beautify -r apps/movies/static/movies/partials/*.html
  - js-beautify -r apps/movies/static/movies/js/*.js
  - phantomjs -v
  - karma start --single-run
